; Meshtastic DIY v1 by Nano VHF Schematic based on ESP32-WROOM-32 (38 pins) devkit & EBYTE E22 SX1262/SX1268 module
[env:meshtastic-diy-v1-rxtx-ru]
custom_meshtastic_hw_model = 39
custom_meshtastic_hw_model_slug = HYDRA
custom_meshtastic_architecture = esp32
custom_meshtastic_actively_supported = true
custom_meshtastic_support_level = 3
custom_meshtastic_display_name = Hydra
custom_meshtastic_tags = DIY

extends = esp32_base
board = esp32doit-devkit-v1

lib_ignore =
    ESP32 BLE Arduino
    BLE
    
build_flags =
  ${esp32_base.build_flags}
  -D DIY_V1
  -I variants/esp32/diy/hydra
  -D EBYTE_E22
  ;-D PRIVATE_HW
  -D OLED_RU
  -D SX126X_RXEN=14
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -D MESHTASTIC_EXCLUDE_WEBSERVER=1

custom_sdkconfig =
    CONFIG_BT_ENABLED=y
    CONFIG_BTDM_CTRL_MODE_BLE_ONLY=y
    CONFIG_BT_BLUEDROID_ENABLED=n
    CONFIG_BT_NIMBLE_ENABLED=y
    CONFIG_BT_NIMBLE_NVS_PERSIST=y
    CONFIG_BT_NIMBLE_ROLE_CENTRAL=n
    CONFIG_BT_NIMBLE_ROLE_OBSERVER=n
    CONFIG_BT_CONTROLLER_ENABLED=y
    CONFIG_BT_NIMBLE_MAX_BONDS=6
    CONFIG_BT_NIMBLE_MAX_CCCDS=8
    CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=5120
    CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1


; [env:meshtastic-diy-v1-rxtx-ru]
; extends = esp32_base
; board = esp32doit-devkit-v1
; board_check = true

; lib_ignore =
;     ESP32 BLE Arduino
;     BLE   ; ← Это главное!

; lib_deps =
;     ${esp32_base.lib_deps}
;     ;h2zero/NimBLE-Arduino@^1.4.0     ; ← Добавьте эту строку

; build_flags =
;   ${esp32_base.build_flags}
;   -D DIY_V1
;   -D EBYTE_E22
;   ;-D PRIVATE_HW
;   -D OLED_RU
;   -D SX126X_RXEN=14
;   -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
;   -D MESHTASTIC_EXCLUDE_WEBSERVER=1
;   -I variants/esp32/diy/v1_rxtx
; ; === NimBLE настройки ===
;   -D CONFIG_BT_ENABLED=1
;   -D CONFIG_BT_NIMBLE_ENABLED=1
;   -D CONFIG_BTDM_CONTROLLER_MODE_BLE_ONLY=1
;   -D CONFIG_BT_NIMBLE_MAX_BONDS=6
;   -D CONFIG_BT_NIMBLE_MAX_CCCDS=20
;   -D CONFIG_BT_NIMBLE_HOST_TASK_STACK_SIZE=8192
;   -D CONFIG_NIMBLE_CPP_LOG_LEVEL=1
;   -DMYNEWT_VAL_BLE_HS_LOG_LVL=LOG_LEVEL_CRITICAL



[env:meshtastic-diy-v1-rxtx-ru-tst]
extends = esp32_base
board = esp32doit-devkit-v1
board_check = true
lib_ignore = BLE
build_flags =
  ${esp32_base.build_flags}
  -D DIY_V1
  -D EBYTE_E22
  ;-D PRIVATE_HW
  -D OLED_RU
  -I variants/esp32/diy/v1_rxtx
  -D MESHTASTIC_EXCLUDE_PAXCOUNTER=1
  -D MESHTASTIC_EXCLUDE_WEBSERVER=1
  ;-D DEBUG_HEAP=1

